### ISSUE TITLE
error when running

### ISSUE THREAD

**Issue by adamzki99** [adamzki99/rasp_pi_workshop#1]
Traceback (most recent call last):
  File "example.py", line 47, in <module>
    main()
  File "example.py", line 26, in main
    h = am2302.humidity
  File "/usr/local/lib/python3.7/dist-packages/adafruit_dht.py", line 269, in humidity
    self.measure()
  File "/usr/local/lib/python3.7/dist-packages/adafruit_dht.py", line 211, in measure
    raise RuntimeError("DHT sensor not found, check wiring")
RuntimeError: DHT sensor not found, check wiring

**Comment by birk-brunell** [comment]
# ?

**Comment by birk-brunell** [comment]
> Traceback (most recent call last): File "example.py", line 47, in main() File "example.py", line 26, in main h = am2302.humidity File "/usr/local/lib/python3.7/dist-packages/adafruit_dht.py", line 269, in humidity self.measure() File "/usr/local/lib/python3.7/dist-packages/adafruit_dht.py", line 211, in measure raise RuntimeError("DHT sensor not found, check wiring") RuntimeError: DHT sensor not found, check wiring

?
